// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace PddOpenSdk.Models.PddApiResponse
{

    public class AdPlanCreateResponse
    {

        /// <summary>
        /// Examples: 1267
        /// </summary>
        [JsonProperty("ad_plan_id")]
        public int AdPlanId { get; set; }
    }

    public class CreateAdPlanResponseModel
    {

        /// <summary>
        /// Examples: {"ad_plan_id":1267}
        /// </summary>
        [JsonProperty("ad_plan_create_response")]
        public AdPlanCreateResponse AdPlanCreateResponse { get; set; }
    }

}
