// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace PddOpenSdk.Models.PddApiResponse
{

    public class WeappQrcodeGenerateResponse
    {

        /// <summary>
        /// Examples: "http://xcxcdn.yangkeduo.com/duobaoSpread/2543453159/1000098_11919498/2.jpg"
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public class GenDdkWeappQrcodeUrlResponseModel
    {

        /// <summary>
        /// Examples: {"url":"http://xcxcdn.yangkeduo.com/duobaoSpread/2543453159/1000098_11919498/2.jpg"}
        /// </summary>
        [JsonProperty("weapp_qrcode_generate_response")]
        public WeappQrcodeGenerateResponse WeappQrcodeGenerateResponse { get; set; }
    }

}
