// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace PddOpenSdk.Models.PddApiResponse
{

    public class AdPlanCreateResponse
    {

        /// <summary>
        /// Examples: true
        /// </summary>
        [JsonProperty("creatable")]
        public bool Creatable { get; set; }
    }

    public class PlanAdCanCreateResponseModel
    {

        /// <summary>
        /// Examples: {"creatable":true}
        /// </summary>
        [JsonProperty("ad_plan_create_response")]
        public AdPlanCreateResponse AdPlanCreateResponse { get; set; }
    }

}
